"""add reconciliation_schedules

Revision ID: 0012_reconciliation_schedules
Revises: 0011_webhook_null_job
Create Date: 2026-05-26 00:09:33.928996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0012_reconciliation_schedules'
down_revision: Union[str, None] = '0011_webhook_null_job'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('api_keys_key_hash_key'), 'api_keys', type_='unique')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.alter_column('audit_logs', 'job_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_index(op.f('ix_bank_entries_tenant_cleared'), table_name='bank_entries')
    op.drop_index(op.f('ix_bank_entries_value_date'), table_name='bank_entries')
    op.create_index(op.f('ix_bank_entries_tenant_id'), 'bank_entries', ['tenant_id'], unique=False)
    op.alter_column('matches', 'job_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_index(op.f('ix_transaction_buffer_tenant_status'), table_name='transaction_buffer')
    op.create_index(op.f('ix_transaction_buffer_status'), 'transaction_buffer', ['status'], unique=False)
    op.create_index(op.f('ix_transaction_buffer_tenant_id'), 'transaction_buffer', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_vendor_rules_tenant'), table_name='vendor_rules')
    op.drop_constraint(op.f('uq_vendor_rules_payee_field'), 'vendor_rules', type_='unique')
    op.create_index(op.f('ix_vendor_rules_tenant_id'), 'vendor_rules', ['tenant_id'], unique=False)
    op.create_table(
        'reconciliation_schedules',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('tenant_id', sa.String(36), sa.ForeignKey('tenants.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('run_time_utc', sa.String(5), nullable=False),
        sa.Column('days_of_week', sa.JSON(), nullable=False),
        sa.Column('bank_account_id', sa.String(36), sa.ForeignKey('bank_accounts.id', ondelete='CASCADE'), nullable=False),
        sa.Column('base_currency', sa.String(3), nullable=False, server_default='MYR'),
        sa.Column('enabled', sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column('created_at', sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_rules_tenant_id'), table_name='vendor_rules')
    op.create_unique_constraint(op.f('uq_vendor_rules_payee_field'), 'vendor_rules', ['tenant_id', 'payee_pattern', 'field_name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_vendor_rules_tenant'), 'vendor_rules', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_transaction_buffer_tenant_id'), table_name='transaction_buffer')
    op.drop_index(op.f('ix_transaction_buffer_status'), table_name='transaction_buffer')
    op.create_index(op.f('ix_transaction_buffer_tenant_status'), 'transaction_buffer', ['tenant_id', 'status'], unique=False)
    op.alter_column('matches', 'job_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_index(op.f('ix_bank_entries_tenant_id'), table_name='bank_entries')
    op.create_index(op.f('ix_bank_entries_value_date'), 'bank_entries', ['value_date'], unique=False)
    op.create_index(op.f('ix_bank_entries_tenant_cleared'), 'bank_entries', ['tenant_id', 'cleared'], unique=False)
    op.alter_column('audit_logs', 'job_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=False)
    op.create_unique_constraint(op.f('api_keys_key_hash_key'), 'api_keys', ['key_hash'], postgresql_nulls_not_distinct=False)
    op.drop_table('reconciliation_schedules')
    # ### end Alembic commands ###
